[2017-12-13 10:44:49,685]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 10:45:00,847]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 10:45:09,796]-[root]-[92]-[INFO]-[stage two compelet.]
[2017-12-13 11:01:15,432]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:01:26,482]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 11:01:58,638]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:02:09,604]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 11:02:16,412]-[root]-[92]-[INFO]-[stage two compelet.]
[2017-12-13 11:03:08,005]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:03:19,417]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 11:03:22,006]-[root]-[92]-[INFO]-[stage two compelet.]
[2017-12-13 11:03:37,819]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:03:48,988]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 11:03:53,598]-[root]-[92]-[INFO]-[stage two compelet.]
[2017-12-13 11:16:42,722]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:16:53,200]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:17:04,762]-[root]-[82]-[INFO]-[stage one compelet.]
[2017-12-13 11:17:09,486]-[root]-[93]-[INFO]-[stage two compelet.]
[2017-12-13 11:17:19,982]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:17:29,075]-[root]-[84]-[ERROR]-['int' object has no attribute 'fit']
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 77, in stage_one
    self.__oof_train_all = np.hstack(tuple(map(get_oof_train, model_list)))
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 58, in get_oof_train
    model.fit(x_train, y_train)
AttributeError: 'int' object has no attribute 'fit'
[2017-12-13 11:17:43,411]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:17:52,801]-[root]-[84]-[ERROR]-['int' object has no attribute 'fit']
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 77, in stage_one
    self.__oof_train_all = np.hstack(tuple(map(get_oof_train, model_list)))
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 58, in get_oof_train
    model.fit(x_train, y_train)
AttributeError: 'int' object has no attribute 'fit'
[2017-12-13 11:18:41,706]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:18:50,660]-[root]-[84]-[ERROR]-['int' object has no attribute 'fit']
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 77, in stage_one
    self.__oof_train_all = np.hstack(tuple(map(get_oof_train, model_list)))
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 58, in get_oof_train
    model.fit(x_train, y_train)
AttributeError: 'int' object has no attribute 'fit'
[2017-12-13 11:33:39,553]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:33:48,194]-[root]-[84]-[ERROR]-['int' object has no attribute 'fit']
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 77, in stage_one
    self.__oof_train_all = np.hstack(tuple(map(get_oof_train, model_list)))
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 58, in get_oof_train
    model.fit(x_train, y_train)
AttributeError: 'int' object has no attribute 'fit'
[2017-12-13 11:34:27,809]-[root]-[38]-[INFO]-[train test split compelet.]
[2017-12-13 11:34:36,681]-[root]-[84]-[ERROR]-['int' object has no attribute 'fit']
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 77, in stage_one
    self.__oof_train_all = np.hstack(tuple(map(get_oof_train, model_list)))
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 58, in get_oof_train
    model.fit(x_train, y_train)
AttributeError: 'int' object has no attribute 'fit'
[2017-12-13 11:34:36,764]-[root]-[95]-[ERROR]-[Input arrays should have the same number of samples as target arrays. Found 0 input samples and 12705 target samples.]
Traceback (most recent call last):
  File "D:/Code/Python/Python_Study_Note/Project/LostRepair/FifthStep/Main.py", line 88, in stage_two
    model.fit(self.__train_all, self.__train_label, batch_size=100, epochs=4)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\keras\engine\training.py", line 1574, in fit
    batch_size=batch_size)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\keras\engine\training.py", line 1419, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "C:\Users\Dell\Anaconda3\lib\site-packages\keras\engine\training.py", line 250, in _check_array_lengths
    'and ' + str(list(set_y)[0]) + ' target samples.')
ValueError: Input arrays should have the same number of samples as target arrays. Found 0 input samples and 12705 target samples.
